### ISSUE TITLE
Does not work with Magento 2.2.2 / zendframework1 dependency issue

### ISSUE THREAD

**Issue by alienvenom** [Magenerds/Ldap#6]
Problem 1
    - Conclusion: remove magento/zendframework1 1.13.1
    - Conclusion: remove magento/product-community-edition 2.2.2
    - Installation request for magenerds/ldap ~2.0 -> satisfiable by magenerds/ldap[2.0.0].
    - Installation request for magento/product-community-edition 2.2.2 -> satisfiable by magento/product-community-edition[2.2.2].
    - magenerds/ldap 2.0.0 requires magento/zendframework1 ~1.12.16 -> satisfiable by magento/zendframework1[1.12.16, 1.12.16-patch1, 1.12.16-patch2, 1.12.16-patch3].
    - Can only install one of: magento/zendframework1[1.13.0, 1.12.16].
    - Can only install one of: magento/zendframework1[1.13.0, 1.12.16-patch1].
    - Can only install one of: magento/zendframework1[1.13.0, 1.12.16-patch2].
    - Can only install one of: magento/zendframework1[1.13.0, 1.12.16-patch3].
    - magento/product-community-edition 2.2.2 requires magento/zendframework1 ~1.13.0 -> satisfiable by magento/zendframework1[1.13.1, 1.13.0].
    - Conclusion: don't install magento/zendframework1 1.13.1

**Comment by sydekumf** [comment]
Thanks! Fixed in https://github.com/Magenerds/Ldap/releases/tag/2.0.1

**Comment by alienvenom** [comment]
Got another issue for you, this time against magento/framework 101.0.2

 Problem 1
    - Installation request for magenerds/ldap 2.0.1 -> satisfiable by magenerds/ldap[2.0.1].
    - Conclusion: remove magento/framework 101.0.2
    - magento/product-community-edition 2.2.2 requires magento/framework 101.0.2 -> satisfiable by magento/framework[101.0.2].
    - magento/product-community-edition 2.2.2 requires magento/framework 101.0.2 -> satisfiable by magento/framework[101.0.2].
    - Conclusion: don't install magento/framework 101.0.2
    - Installation request for magento/product-community-edition 2.2.2 -> satisfiable by magento/product-community-edition[2.2.2].

**Comment by sydekumf** [comment]
What is your composer.json?

**Comment by davidangel** [comment]
```
  Problem 1
    - Conclusion: don't install magenerds/ldap 2.0.1
    - Installation request for magento/framework (locked at 101.0.2) -> satisfiable by magento/framework[101.0.2].
    - Conclusion: remove magento/zendframework1 1.13.1
    - Installation request for magenerds/ldap ~2.0 -> satisfiable by magenerds/ldap[2.0.0, 2.0.1].
    - Conclusion: don't install magento/zendframework1 1.13.1
    - magenerds/ldap 2.0.0 requires magento/zendframework1 ~1.12.16 -> satisfiable by magento/zendframework1[1.12.16, 1.12.16-patch1, 1.12.16-patch2, 1.12.16-patch3, 1.12.x-dev].
    - Can only install one of: magento/zendframework1[1.12.16, 1.13.1].
    - Can only install one of: magento/zendframework1[1.12.16-patch1, 1.13.1].
    - Can only install one of: magento/zendframework1[1.12.16-patch2, 1.13.1].
    - Can only install one of: magento/zendframework1[1.12.16-patch3, 1.13.1].
    - Can only install one of: magento/zendframework1[1.12.x-dev, 1.13.1].
    - Installation request for magento/zendframework1 (locked at 1.13.1) -> satisfiable by magento/zendframework1[1.13.1].
```
